### ISSUE TITLE
code of  Parallel z-buffering algorithm

### ISSUE THREAD

**Issue by xjturobocon** [arthurhero/ZbuffDepth#2]
Hi, thanks for sharing. I have a question on the code. Concretely, In ZbufferDepth/ops.py:
` #since the rows are not operated simultaneously, we only copy the depth row

    depth_row = pc[0].clone() # x's
    reg.index_copy_(0,idx_abs,depth_row)`
Why did you choose to use pc[0] but not pc[2]? I think pc[2] represent depth and pc[0] is just x. Z-buffer algorithm need to choose smaller depth, right?
Hope for your reply.

**Comment by arthurhero** [comment]
Hi, thanks for asking. There are different coordinate systems used by KITTI. In the image coordinates, z is forward, while in laser coordinates, x is forward. The point clouds are in the laser coordinates (after inverse camera intrinsics).
